# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x1f\n\x0eGetDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\x0fGetDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2@\n\x0e\x45xampleService\x12.\n\x07GetData\x12\x0f.GetDataRequest\x1a\x10.GetDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETDATAREQUEST']._serialized_start=16
  _globals['_GETDATAREQUEST']._serialized_end=47
  _globals['_GETDATARESPONSE']._serialized_start=49
  _globals['_GETDATARESPONSE']._serialized_end=82
  _globals['_EXAMPLESERVICE']._serialized_start=84
  _globals['_EXAMPLESERVICE']._serialized_end=148
# @@protoc_insertion_point(module_scope)
